# http://travis-ci.org/#!/jupyter/jupyterhub
language: python
python:
  - 3.8
  - 3.7
  - 3.6
install:
  - pip install --upgrade pip setuptools pbr wheel
  - python setup.py bdist_wheel
  - pip install dist/*.whl -r dev-requirements.txt
script:
  - py.test --cov=hubshare hubshare/tests -v
after_success:
  - codecov
